### ISSUE TITLE
Raccoon suit and Kitsune suit mischief

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#11]
Some craziness happening here.

Using the Raccoon suit's power, once activated causes some odd behavior.  There's a clear mix-up with these two powers.

[Raccoon suit and Kitsune suit mischief](https://youtu.be/4RJ5EUgRRpM)

**Comment by dahrkdaiz** [comment]
That's suck a goober mistake of mine! I've fixed it!
