### ISSUE TITLE
Locked Door/Key Glitched

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#13]
[Locked Door/Key glitched](https://youtu.be/oYVbPuNOGyE)

I am not sure exactly what causes this but it seems to happen when I start the level with the Raccoon suit. It's likely a combination of multiple things I am doing in the level but it's hit and miss.

I will continue to isolate this bug if possible.

**Comment by KingKoopa94** [comment]
Had this same issue the first time I did the level, I was just big mario, and went sprinting passed the door.
Thankfully you can go thru the little half door if this happens

**Comment by dahrkdaiz** [comment]
I *think* I fixed this. I was able to reproduce it twice and it's been a bug I've experienced on and off, but haven't been able to reproduce it since I put in the fix.
