### ISSUE TITLE
Able To Kill Piranha Plant Through Pipe

### ISSUE THREAD

**Issue by MrP4RK3R** [dahrkdaiz/smb3project#14]
In the section of the underground level when there are 3 green pipes about 3/4 of the way submerged in water, the middle pipe houses a piranha plant enemy.  I'm able to kill the plant by firing projectiles to the outside of the pipe while the plant is ducked inside.  I fire the projectiles into the side of the pipe when the plant should be safely housed, yet the plant still bursts inside the pipe as if it's been hit with the projectiles.  It happens when firing the fireballs, the ninja stars, and the hammers.  I've been able to replicate it every time I've tried.

**Comment by dahrkdaiz** [comment]
This should now be fixed. The Piranha should be safe from harm as long as it's completely inside its pipe.
