### ISSUE TITLE
Items stuck in walls

### ISSUE THREAD

**Issue by leftypem** [dahrkdaiz/smb3project#15]
Ran int a situation yesterday where, while pressed up against a wall and letting go of the spring platform would cause it to get lodged in the wall, making the level unbeatable without taking a trip through pipes to reset the level items.

**Comment by dahrkdaiz** [comment]
What version of the ROM were you using?

**Comment by leftypem** [comment]
11/28 Stacks of Enemies

**Comment by dahrkdaiz** [comment]
This should be fixed in the current version (12/4 Subcon Returns)
