### ISSUE TITLE
P-meter level tweaking out

### ISSUE THREAD

**Issue by leftypem** [dahrkdaiz/smb3project#16]
After several bouts of using glitched raccoon mario's "fireball" power, the P-Meter first triangle would just blink on and off while I was standing still. Maxing the gauge and letting it drain would not fix the issue. This was obsevered in the underground cavern.

https://youtu.be.o0NKKUdeaQl

**Comment by dahrkdaiz** [comment]
Raccoon Mario using the Fire Dash glitch was fixed, so I assume this glitch wouldn't happen either as a result.
