### ISSUE TITLE
Scanline tearing

### ISSUE THREAD

**Issue by leftypem** [dahrkdaiz/smb3project#17]
In certain areas, a tearing effect can be seen in the sprite layer. Have witnessed in Stacks and Underground.

This occurs on Famicom with Everdrive. Have yet to test with Playchoice and Powerpak.

https://youtu.be/wLeWuKAuLqA

**Comment by dahrkdaiz** [comment]
Is this on actual hardware? I've not seen this issue ever before.

**Comment by leftypem** [comment]
Actual hardware. I'll try to make more videos, but I have very limited phone space, so it may take time to shoot, upload, and delete
I'll also try and see if its related to certain suits or visible items in each instance

**Comment by dahrkdaiz** [comment]
That's fine. I may see if the other testers with actual hardware have the same issue.

**Comment by AngealZC** [comment]
I can put it on my PowerPak when I get home tonight. I guess I wasn't exactly sure what was being referred to in the video though.

**Comment by dahrkdaiz** [comment]
in the video, just below the green part of the ground, it bends to the right. It almost look like the TV itself is doing it, but I can't be sure without someone else trying it.

**Comment by AngealZC** [comment]
Alright, I see that now. I'll check that tonight.

**Comment by EdGe7x** [comment]
Not seeing this on my Powerpak/Top Loader/LCD TV setup.

**Comment by leftypem** [comment]
Only seems to happen during day cycles.

**Comment by EdGe7x** [comment]
Have you tried a different TV?

**Comment by leftypem** [comment]
It's not technically a scan line issue, as it affects the same line of terrain if I move above it. Will upload more video Monday

**Comment by AngealZC** [comment]
I tried it on my Powerpak/Front Load/LED. I don't notice anything of the sort. I don't have a CRT tv available, otherwise I would try that.

**Comment by KingKoopa94** [comment]
Waiting on my INL programmer, so soon I'll be able to flash all the test levels to a cart.
Have a front loader with a good ol' Sony Trinitron, can't wait to see how it looks on a CRT.

**Comment by KingKoopa94** [comment]
I know what's causing the issue. The contacts on your Everdrive are not making a perfect connection to the pins on your system. I had this issue when I first bought my NES, and I commonly experience this when using a Famicom to NES converter.

I do not think this is a game issue, just more of an issue of dirty pins or the game pak not making a perfect connection. These old systems are finicky!

**Comment by leftypem** [comment]
Hmm. I'll confirm against the Playchoice arcade tonight, and attempt to reseat my cartridge in the Famicom.

**Comment by leftypem** [comment]
Not happening on the Playchoice. Looks like it's probably gonna be my old hardware, which is odd as it doesn't affect any other games I've played on it.

**Comment by dahrkdaiz** [comment]
I'm closing this since it seems to be specific hardware instance and not programming related.
