### ISSUE TITLE
Underground Cavern moving platforms vanish/dont spawn properly

### ISSUE THREAD

**Issue by leftypem** [dahrkdaiz/smb3project#18]
Likely due to too many sprites per scanline.

Using Ninja Mario to scale the wall to the right of the 2nd moving platform in Underground Cavern will cause heavy sprite flicker to the platform, at times making it almost invisible. Likewise, hanging from the rope between them as certain suits will cause flickering and occasionally despawn the right platform unless a "leap of faith" is made which causes it to spwan later than its normal timed rotation.

**Comment by dahrkdaiz** [comment]
I've made the platforms rotating in a circle instead so that the scanline issue is limited. The despawning issue I cannot seem to reproduce. Despawning should only really happen when the platform is back to it's original point AND is 40 pixels off screen. But I'll do some more testing.
