### ISSUE TITLE
Throwing necessary items off screen

### ISSUE THREAD

**Issue by leftypem** [dahrkdaiz/smb3project#20]
Something I noticed in regards to activating too many ? blocks. If you are in an area where you can throw them out of bounds, they still remain active, and therefore new ? blocks can not be used. Out of boundary walls may need to be added to keep players from throwing away possibly necessary items. this behavior can be replicated in the first screen of Underground Caverns.

**Comment by dahrkdaiz** [comment]
The first screen of Underground Hunt only has one ? block with an item inside it. Can you be more specific on how you reproduced this?

**Comment by dahrkdaiz** [comment]
Also, I've modified this level to prevent the key from being thrown into a pit.

**Comment by dahrkdaiz** [comment]
I was unable to throw a key into the wall, but I will try to do this with the spring.

**Comment by leftypem** [comment]
In the 12/3 demo, the first screen ? blocks present you with multiple keys, and throwing them off screen results in the other blocks not activating. I suppose I was more concerned with this glitch happening further down the road where the items in the ? blocks would actually be required to get through a level.

**Comment by leftypem** [comment]
I haven't tried getting a spring stuck in a wall yet with the latest demo, but it was rather easy in the 11/28 version. A friend here last night even got a koopa shell stuck in a wall somehow, though I couldnt reproduce it.

**Comment by dahrkdaiz** [comment]
Yeah, this was an bug I fixed before it was reported.
