### ISSUE TITLE
Web "vines" in left area of Hunting Underground

### ISSUE THREAD

**Issue by AngealZC** [dahrkdaiz/smb3project#21]
In the original test file for this level, these web "vines" appeared correctly, and were  functional. Now they do not show up at all. Instead, they are solid black blocks. I took some screenshots of Mario standing on, pressing against, and throwing fireballs at.
![retroarch-1204-112733](https://cloud.githubusercontent.com/assets/24373477/20867971/2758423a-ba16-11e6-945c-a0a3e0faf0f3.png)
![retroarch-1204-112815](https://cloud.githubusercontent.com/assets/24373477/20867972/275dc12e-ba16-11e6-9ad6-1894d3966c2f.png)
![retroarch-1204-112820](https://cloud.githubusercontent.com/assets/24373477/20867974/27674ad2-ba16-11e6-99b0-ed54f17d2664.png)
![retroarch-1204-112826](https://cloud.githubusercontent.com/assets/24373477/20867973/2762be0e-ba16-11e6-9294-19636ea04591.png)
![retroarch-1204-112842](https://cloud.githubusercontent.com/assets/24373477/20867975/276a70f4-ba16-11e6-8c68-86d0acb4aa57.png)
![retroarch-1204-112927](https://cloud.githubusercontent.com/assets/24373477/20867976/276cef0a-ba16-11e6-9452-dab336a93b99.png)
![retroarch-1204-112937](https://cloud.githubusercontent.com/assets/24373477/20867977/276fc086-ba16-11e6-95f2-ff028fc3154f.png)

**Comment by dahrkdaiz** [comment]
Thanks! Fixed.
