### ISSUE TITLE
Ninja suit phasing through floor

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#25]
The mysterious powers of the Ninja suit!

[Ninja suit phasing through floor](https://youtu.be/Y6vREoRrY_w)

**Comment by EdGe7x** [comment]
Tried a different suit... not particular to the Ninja suit, happens even as small Mario.

**Comment by KingKoopa94** [comment]
It seems to be an issue with the level, and how the teleport works.
If you stay over to the right side, you get teleported to far over.

**Comment by KingKoopa94** [comment]
More supporting my theory that you end up teleported to another area:
https://youtu.be/k-ub1MH5x9o

**Comment by EdGe7x** [comment]
Now I want to know what level that is. =D

**Comment by KingKoopa94** [comment]
Same, I'm starting to get better at playing it LOL

**Comment by dahrkdaiz** [comment]
This fixed in the current version, which should be released later tonight.
