### ISSUE TITLE
Holding Left While Starting Subcon Returns Kills You!

### ISSUE THREAD

**Issue by KingKoopa94** [dahrkdaiz/smb3project#29]
If you are small Mario, and hold left when you start the level Subcon Returns, you will start the level inside a block and be instantly killed.

Sort of the same happens with big Mario, except you just get hurt and lose your power-up, but end up getting pushed right out of the block.

**Comment by dahrkdaiz** [comment]
This is fixed in the latest version I have, which will be released later this evening.
