### ISSUE TITLE
Kitsune (Fire Fox) Suit Issues

### ISSUE THREAD

**Issue by KingKoopa94** [dahrkdaiz/smb3project#3]
The Kitsune (aka Fire Fox) suit, attacks the opposite way you are facing no matter what. In the video below I have my buttons showing, so you can see what button/combo is being pressed.
A second issue, which I didn't feel needed a second post, is if you spam B fast enough (or have turbo) it will enable the Kitsune flying mode very briefly, and using turbo does the same but causes slowdown.

https://youtu.be/wL1Jd2LsJiU

**Comment by dahrkdaiz** [comment]
This was unintended. You're supposed to have to double tap the B button to activate the fire dash. I've disabled the ability to dash while holding down and made it so you always have to double tap. This causes you to always go the direction you expect.
