### ISSUE TITLE
Vine plant stopped

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#31]
Here's a good example of how fixing a bug in a different level is affecting another level. I am fairly certain that the power-up fix implemented for the Underground Hunting level has caused a bug in which the vine plant stops in Subcon Returns. At this point, the only way out is to intentionally die because you can't get out of that area without the plant or Ninja suit.

This might be an acceptable result... since dying and trying again is what Mario games are all about.

[Vine plant stopped](https://youtu.be/aG6zbJscdlI)

**Comment by dahrkdaiz** [comment]
Oh woops! This is a game breaker imo. I'm working on making the vine able to exist with other power ups, so that should at least fix issues where a vine is required.
