### ISSUE TITLE
Vine Skywalking Issue

### ISSUE THREAD

**Issue by KingKoopa94** [dahrkdaiz/smb3project#33]
If you press left or right and up while climbing the red vine at the start of Floaty Waters you will end up walking on nothing. This extends thru the whole level and only goes away when you jump or get hit by an enemy.

https://youtu.be/X4CvXeIBkRA

**Comment by EdGe7x** [comment]
Replicated.

**Comment by KingKoopa94** [comment]
Checked to see if this was still in the newest version, and it is.

**Comment by dahrkdaiz** [comment]
Fixed!
