### ISSUE TITLE
Locked myself out from progressing due to ice power 

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#35]
Due to the ice power I am unable to progress through level. Only way to move forward is to intentionally die. Removing the Ice Power from this area will help but if someone starts the level with Ice Power then they could end up in the same spot.

May not be a bug but I thought I would bring it up.

[Locked myself out from progressing due to ice power](https://youtu.be/5ED1UrrySjQ)

**Comment by dahrkdaiz** [comment]
Fixed! I've made it so the ice is now "thin". If you grab an object and land on the ice, it bursts. Kind of a cool mechanic to add!
