### ISSUE TITLE
Break in waterfall surface

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#42]
At the risk of sounding like an idiot...the surface line on the left side of a waterfall in Veggie Pickin is missing (obviously).  I tried a ton of shit to see if it was pointing out a secret, but to no avail...graphical error?  It is more noticeable during the night sequence. See pics
![img_2498](https://cloud.githubusercontent.com/assets/6308005/21947186/d5609b4c-d9b1-11e6-9b0a-e5c0d8638c59.JPG)
![img_2499](https://cloud.githubusercontent.com/assets/6308005/21947191/db939d48-d9b1-11e6-84d7-9275158a75f1.JPG)

**Comment by dahrkdaiz** [comment]
Fixed.
