### ISSUE TITLE
Underwater coins have noticeable box outline in Hurricane Mario

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#46]
Since these underwater coins are attainable via touch, there shouldn't be a box outline making you think it's an underwater coin box.  See pic
![img_2511](https://cloud.githubusercontent.com/assets/6308005/21966629/daab7baa-db44-11e6-890e-142807cfe497.JPG)

**Comment by dahrkdaiz** [comment]
Fixed.
