### ISSUE TITLE
Hurricane Mario - open sesame

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#50]
Occurred immediately after using Firefox Mario's fireball move to break the upper bricks blocking the entrance.  I had missed the target, and hit one of the unbreakable sprites, bouncing me back and thru the locked door.  Located very beginning of Hurricane Mario level.  (My son Logan thinks he's a comedian.). See vids:

Part 1: 
https://youtu.be/Hxrs8r_k7Y8

Part 2:
https://youtu.be/Pv3yrz4yiBU

**Comment by dahrkdaiz** [comment]
This should be fixed.
