### ISSUE TITLE
Rhythm and Blocks - the "in between zone"

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#52]
I found a way to be forced into the "in between zone" in Rhythm and Blocks...this may not be an issue that needs fixing, simply because the only way I was able to actually get up past the third note block was to do it as small Mario, then use B+select to become big, then allow the appearing block to make me small and force me thru the wall.  See vid: https://youtu.be/vM35EJjiYYI

**Comment by RetroMarine** [comment]
Btw I enjoyed this level and anti gravity aquarium IMMENSELY!  Great level design, intuitive, and the secrets weren't ridiculously easy to find...I love how the vine above the ice pond in anti gravity aquarium diverts your attention upward, when the real secret is below the ice!

**Comment by dahrkdaiz** [comment]
That's a good point! Do you think the nearby hidden star should be moved to under the ice?

**Comment by RetroMarine** [comment]
I can't think back to where it was, but I thought everything was in a good strategic place.  It's up to you!
