### ISSUE TITLE
Colossal Cheep Challenge - suicide pipe?

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#55]
First pipe kills you.  Is this on purpose? 
https://youtu.be/0uhXAdwouC8

**Comment by dahrkdaiz** [comment]
Wut, no, that's not on purpose at all! XD

**Comment by RetroMarine** [comment]
Hahaha!  I was unsure because it was so blatantly obvious.  I spent about 15 minutes trying to get past the part where the water filled the room after hitting the switch, but to no avail.  The water level wasn't high enough to jump onto the platforms, and I couldn't find a hidden box to use, so I gave up.  Am I missing something, or does the suicide pipe have something to do with it?

**Comment by dahrkdaiz** [comment]
Actually, the pipe is supposed to be the exit route. The idea is that this level requires a number of stars to pass the door.  If you lack that number, it'll take what you have and you can leave the level through the pipe. This has been fixed.
