### ISSUE TITLE
Death after finishing level

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#7]
Not sure if this is a "bug" but I'll throw it in there because if I had just finished a hard level and I died after actually beating it, I would probably be a little upset. =D

Maybe the delay can be cut down to be instant and the sprite animation can occur afterwards... not sure.

[Death after finishing level](https://youtu.be/2SjfCT8YvY4)

**Comment by dahrkdaiz** [comment]
There actually isn't a delay. The game was set to destroy the enemies once you touched the ground, but I've changed it so the enemies die as soon as the poison mushroom is destroyed.
