### ISSUE TITLE
P gauge doesn't gradually fill

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#8]
[P gauge doesn't gradually fill](https://youtu.be/7IkMrgBEEbc)

As you run to gain speed, the P gauge is meant to fill up to indicate your are approaching flight!

**Comment by dahrkdaiz** [comment]
The P gauge is actually mean to indicate how much power your power-up has. Once you take flight, the P-Meter shows a full bar to show much much flight time you have, but I can try to make the Raccoon suit show a filling P-Meter.

**Comment by MrP4RK3R** [comment]
This is something I noticed as well.  The reason to have it is so players can see exactly how much "runway" is needed to achieve flight.  In some instances when the "runway" is short, it may take a couple of back-and-forth passes to get the P-meter filled to achieve flight.  When the meter fills gradually, it gives a clearer indication of exactly when flight will be achieved in addition to the whistle noise indicating flight.  A visual indication allows for a better anticipation for timing purposes.  It's not a huge deal.  But in short, a visual indication of a P-meter filling is actually really helpful. =)

**Comment by dahrkdaiz** [comment]
Good news! I was able to get the P-Meter to fill up with raccoon Mario as he runs! But only Raccoon Mario since the P-Meter serves different functions.
